# Generated by Django 5.2.5 on 2025-08-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_userid_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='app.parentprofile')),
            ],
            options={
                'ordering': ['-points', 'pk'],
                'indexes': [models.Index(fields=['-points'], name='app_leaderb_points_b9f874_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent',), name='uniq_leaderboard_per_parent'), models.CheckConstraint(condition=models.Q(('points__gte', 0)), name='leaderboard_points_nonnegative')],
            },
        ),
    ]
